version: "3.3"
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rsxp2019@@
      - MYSQL_DATABASE=rsxp-neon-api-nodejs
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
